# Generated by Django 5.1.2 on 2024-11-04 09:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(blank=True, choices=[('ACTION', 'Action'), ('ADVENTURE', 'Adventure'), ('ANIMATION', 'Animation'), ('BIOGRAPHY', 'Biography'), ('COMEDY', 'Comedy'), ('CRIME', 'Crime'), ('DOCUMENTARY', 'Documentary'), ('DRAMA', 'Drama'), ('FAMILY', 'Family'), ('FANTASY', 'Fantasy'), ('HISTORY', 'History'), ('HORROR', 'Horror'), ('MUSIC', 'Music'), ('MYSTERY', 'Mystery'), ('ROMANCE', 'Romance'), ('SCIENCE_FICTION', 'Science Fiction'), ('SPORT', 'Sport'), ('THRILLER', 'Thriller'), ('WAR', 'War'), ('WESTERN', 'Western')], max_length=20, null=True)),
                ('publish_date', models.DateField()),
                ('duration', models.DurationField()),
                ('producer', models.CharField(max_length=155)),
                ('lead_actors', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_management.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
