# Generated by Django 5.1.2 on 2024-11-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
